let paragraphs = [
    `The first computers were used primarily for numerical calculations. However, as any information can be numerically encoded, people soon realized that computers are capable of general-purpose information processing. Their capacity to handle large amounts of data has extended the range and accuracy of weather forecasting. Their speed has allowed them to make decisions about routing telephone connections through a network and to control mechanical systems such as automobiles, nuclear reactors, and robotic surgical tools. They are also cheap enough to be embedded in everyday appliances and to make clothes dryers and rice cookers “smart.” Computers have allowed us to pose and answer questions that could not be pursued before.`,

    `Before the true power of computing could be realized, therefore, the naive view of calculation had to be overcome. The inventors who laboured to bring the computer into the world had to learn that the thing they were inventing was not just a number cruncher, not merely a calculator. For example, they had to learn that it was not necessary to invent a new computer for every new calculation and that a computer could be designed to solve numerous problems, even problems not yet imagined when the computer was built. They also had to learn how to tell such a general problem-solving computer what problem to solve. In other words, they had to invent programming.`,

    `The earliest known calculating device is probably the abacus. It dates back at least to 1100 BCE and is still in use today, particularly in Asia. Now, as then, it typically consists of a rectangular frame with thin parallel rods strung with beads. Long before any systematic positional notation was adopted for the writing of numbers, the abacus assigned different units, or weights, to each rod. This scheme allowed a wide range of numbers to be represented by just a few beads and, together with the invention of zero in India, may have inspired the invention of the Hindu-Arabic number system. In any case, abacus beads can be readily manipulated to perform the common arithmetical operations—addition, subtraction, multiplication, and division—that are useful for commercial transactions and in bookkeeping.`,

    `CPU is the brain of the computer. All types of data processing operations and all the important functions of a computer are performed by the CPU. It helps input and output devices to communicate with each other and perform their respective operations. It also stores data which is input, intermediate results in between processing, and instructions. The memory unit is responsible for transferring information to other units of the computer when needed. It is also known as an internal storage unit or the main memory or the primary storage or Random Access Memory (RAM) as all these are storage devices. Its size affects speed, power, and performance. There are two types of memory in the computer, which are primary memory and secondary memory.
    `,

    `In a computer, memory refers to the physical devices that are used to store programs or data on a temporary or permanent basis. It is a group of registers. Memory are of two types (i) primary memory, (ii) secondary memory. Primary memory is made up of semiconductors, It is also divided into two types, Read-Only Memory (ROM) and Random Access Memory (RAM). Secondary memory is a physical device for the permanent storage of programs and data(Hard disk, Compact disc, Flash drive, etc.). Primary memory is made up of semiconductors and it is the main memory of the computer system. It is generally used to store data or information on which the computer is currently working, so we can say that it is used to store data temporarily. Data or information is lost when the systems are off.`,

    `Random Access Memory: Primary memory is also called internal memory. This is the main area in a computer where data, instructions, and information are stored. Any storage location in this memory can be directly accessed by the Central Processing Unit. As the CPU can randomly access any storage location in this memory, it is also called Random Access Memory or RAM. The CPU can access data from RAM as long as the computer is switched on. As soon as the power to the computer is switched off, the stored data and instructions disappear from RAM. Such type of memory is known as volatile memory. RAM is also called read/write memory. In secondary memory, a fixed storage is an internal media device that is used to store data in a computer system. Fixed storage is generally known as fixed disk drives or hard drives. Generally, the data of the computer system is stored in a built-in fixed storage device.`,

    `A floppy disk consists of a magnetic disc in a square plastic case. It is used to store data and to transfer data from one device to another device. Floppy disks are available in two sizes (a) Size: 3.5 inches, the Storage capacity of 1.44 MB (b) Size: 5.25 inches, the Storage capacity of 1.2 MB. To use a floppy disk, our computer needs to have a floppy disk drive. This storage device becomes obsolete now and has been replaced by CDs, DVDs, and flash drives. A Compact Disc (CD) is a commonly used secondary storage device. It contains tracks and sectors on its surface. Its shape is circular and is made up of polycarbonate plastic. The storage capacity of CD is up to 700 MB of data. A CD may also be called a CD-ROM (Compact Disc Read-Only Memory), in this computers can read the data present in a CD-ROM, but cannot write new data onto it. For a CD-ROM, we require a CD-ROM. CD is of two types:`,

    ` A Blu-ray disc looks just like a CD or a DVD but it can store data or information up to 25 GB data. If you want to use a Blu-ray disc, you need a Blu-ray reader. The name Blu-ray is derived from the technology that is used to read the disc ‘Blu’ from the blue-violet laser and ‘ray’ from an optical ray. A hard disk is a part of a unit called a hard disk drive. It is used to storing a large amount of data. Hard disks or hard disk drives come in different storage capacities.(like 256 GB, 500 GB, 1 TB, and 2 TB, etc.). It is created using the collection of discs known as platters. The platters are placed one below the other. They are coated with magnetic material. Each platter consists of a number of invisible circles and each circle having the same centre called tracks. A flash drive or pen drive comes in various storage capacities, such as 1 GB, 2 GB, 4 GB, 8 GB, 16 GB, 32 GB, 64 GB, up to 1 TB.`,

    `It is also known as SDD. It is a non-volatile storage device that is used to store and access data. It is faster, does noiseless operations(because it does not contain any moving parts like the hard disk), consumes less power, etc. It is a great replacement for standard hard drives in computers and laptops if the price is low and it is also suitable for tablets, notebooks, etc because they do not require large storage. It is known as a Secure Digital Card. It is generally used in portable devices like mobile phones, cameras, etc., to store data. It is available in different sizes like 1 GB, 2 GB, 4 GB, 8 GB, 16 GB, 32 GB, 64 GB, etc. To view the data stored in the SD card you can remove them from the device and insert them into a computer with help of a card reader. The data stores in the SD card is stored in memory chips(present in the SD Card) and it does not contain any moving parts like the hard disk. `,

    `LAN or Local Area Network connects network devices in such a way that personal computers and workstations can share data, tools, and programs. The group of computers and devices are connected together by a switch, or stack of switches, using a private addressing scheme as defined by the TCP/IP protocol. Private addresses are unique in relation to other computers on the local network. Routers are found at the boundary of a LAN, connecting them to the larger WAN. Data transmits at a very fast rate as the number of computers linked is limited. By definition, the connections must be high speed and relatively inexpensive hardware (Such as hubs, network adapters, and Ethernet cables). LANs cover a smaller geographical area (Size is limited to a few kilometers) and are privately owned. One can use it for an office building, home, hospital, schools, etc. LAN is easy to design and maintain.`,

    `MAN or Metropolitan area Network covers a larger area than that of a LAN and smaller area as compared to WAN. It connects two or more computers that are apart but reside in the same or different cities. It covers a large geographical area and may serve as an ISP (Internet Service Provider). MAN is designed for customers who need high-speed connectivity. Speeds of MAN range in terms of Mbps. It’s hard to design and maintain a Metropolitan Area Network. The fault tolerance of a MAN is less and also there is more congestion in the network. It is costly and may or may not be owned by a single organization. The data transfer rate and the propagation delay of MAN are moderate. Devices used for transmission of data through MAN are Modem and Wire/Cable. Examples of a MAN are the part of the telephone company network that can provide a high-speed DSL line to the customer or the cable TV network in a city. `
]


